# Variables
@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

####

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###
# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Room 1",
  "description": "This is room 1"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###
# Get Questions by Room ID
# @name getQuestionsByRoomId
GET {{baseUrl}}/rooms/{{roomId}}/questions

###
# Create Room
# @name createQuestion
POST {{baseUrl}}/rooms/1c9be4b6-d159-45f0-a1ba-cb5d5526bd1e/questions
Accept: application/json
Content-Type: application/json

{
  "question": "arquivo com silencio"
}